-- MySQL Script generated by MySQL Workbench
-- Thu May 25 01:16:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema npi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema npi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `npi` DEFAULT CHARACTER SET utf8 ;
USE `npi` ;

-- -----------------------------------------------------
-- Table `npi`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npi`.`provider` (
  `number` INT(10) UNSIGNED NOT NULL,
  `enumeration_type` ENUM('NPI-1', 'NPI-2') NOT NULL,
  `replacement_npi` INT(10) NULL,
  `organization_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `name_prefix` VARCHAR(45) NULL,
  `name_suffix` VARCHAR(45) NULL,
  `credential` VARCHAR(45) NULL,
  `created_epoch` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_updated_epoch` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deactivation_reason_code` VARCHAR(45) NULL,
  `deactivation_date` DATE NULL,
  `reactivation_date` DATE NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `authorized_official_last_name` VARCHAR(45) NULL,
  `authorized_official_first_name` VARCHAR(45) NULL,
  `authorized_official_middle_name` VARCHAR(45) NULL,
  `authorized_official_title_or_position` VARCHAR(45) NULL,
  `authorized_official_telephone_number` VARCHAR(45) NULL,
  `authorized_official_name_prefix` VARCHAR(45) NULL,
  `authorized_official_name_suffix` VARCHAR(45) NULL,
  `authorized_official_credential` VARCHAR(45) NULL,
  `ein` INT NULL,
  `sole_proprietor` TINYINT NULL,
  `organizational_subpart` TINYINT NULL,
  `parent_organization_legal_business_name` VARCHAR(45) NULL,
  `parent_organization_ein` VARCHAR(45) NULL,
  `certification_date` DATETIME NULL,
  `status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`number`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `npi`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npi`.`address` (
  `idAddress` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address_purpose` ENUM('MAILING', 'LOCATION', 'PRACTICE', 'ENDPOINT') NOT NULL DEFAULT 'MAILING',
  `address_type` ENUM('DOM', 'FGN', 'MIL') NULL DEFAULT 'DOM',
  `address_1` VARCHAR(45) NOT NULL,
  `address_2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `telephone_number` VARCHAR(45) NULL,
  `fax_number` VARCHAR(45) NULL,
  `country_code` VARCHAR(2) NOT NULL,
  `country_name` VARCHAR(45) NOT NULL,
  `provider_number` INT(10) NOT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fk_address_provider_idx` (`provider_number` ASC) VISIBLE,
  CONSTRAINT `fk_address_provider`
    FOREIGN KEY (`provider_number`)
    REFERENCES `npi`.`provider` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `npi`.`identifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npi`.`identifier` (
  `idIdentifier` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `state` VARCHAR(45) NULL,
  `issuer` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `provider_number` INT(10) NOT NULL,
  PRIMARY KEY (`idIdentifier`),
  INDEX `fk_identifier_provider1_idx` (`provider_number` ASC) VISIBLE,
  CONSTRAINT `fk_identifier_provider1`
    FOREIGN KEY (`provider_number`)
    REFERENCES `npi`.`provider` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `npi`.`taxonomy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npi`.`taxonomy` (
  `idTaxonomy` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(12) NOT NULL,
  `taxonomy_group` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `license` VARCHAR(10) NOT NULL,
  `primary` TINYINT NOT NULL DEFAULT 1,
  `provider_number` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idTaxonomy`),
  INDEX `fk_taxonomy_provider1_idx` (`provider_number` ASC) VISIBLE,
  CONSTRAINT `fk_taxonomy_provider1`
    FOREIGN KEY (`provider_number`)
    REFERENCES `npi`.`provider` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `npi`.`othername`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npi`.`othername` (
  `idOrderName` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT(10) NOT NULL,
  `organization_name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL,
  `type` VARCHAR(45) NOT NULL,
  `provider_number` INT(10) NOT NULL,
  PRIMARY KEY (`idOrderName`),
  INDEX `fk_othername_provider1_idx` (`provider_number` ASC) VISIBLE,
  CONSTRAINT `fk_othername_provider1`
    FOREIGN KEY (`provider_number`)
    REFERENCES `npi`.`provider` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `npi`.`endpoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npi`.`endpoint` (
  `idEndpoint` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` INT(10) NOT NULL,
  `endpointType` ENUM('Direct Address', 'SOAP URL', 'Connect URL', 'FHIR URL', 'Restful URL', 'Website URL', 'Other URL') NOT NULL,
  `endpointTypeDescription` VARCHAR(45) NOT NULL,
  `endpoint` VARCHAR(45) NULL,
  `affiliation` VARCHAR(45) NULL,
  `endpointDescription` VARCHAR(45) NULL,
  `affliationName` VARCHAR(45) NULL,
  `use` VARCHAR(45) NULL,
  `useDescription` VARCHAR(45) NULL,
  `useOtherDescription` VARCHAR(45) NULL,
  `contentType` VARCHAR(45) NULL,
  `contentTypeDescription` VARCHAR(45) NULL,
  `contentOtherDescription` VARCHAR(45) NULL,
  `address_idAddress` INT UNSIGNED NOT NULL,
  `provider_number` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idEndpoint`),
  INDEX `fk_endpoint_address1_idx` (`address_idAddress` ASC) VISIBLE,
  INDEX `fk_endpoint_provider1_idx` (`provider_number` ASC) VISIBLE,
  CONSTRAINT `fk_endpoint_address1`
    FOREIGN KEY (`address_idAddress`)
    REFERENCES `npi`.`address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endpoint_provider1`
    FOREIGN KEY (`provider_number`)
    REFERENCES `npi`.`provider` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
